
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      # show_sql: true
      # format_sql: true

oauth:
  kakao:
    client_id: 432a025ef4e00638dd7d485fcab9a342
    secret_id: apc3QffqOdNXbVsPo25b3tUwU0p3uyVc
    redirect_url: http://localhost:8080/auth/kakao